[window]
opacity = 0.9

[font]
size = 8

[font.bold]
family = "Hack Nerd Font Propo"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Propo"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font Propo"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Propo"
style = "Regular"

# One dark theme
# https://github.com/sudosubin/one-dark-alacritty/blob/main/config.yml
[colors.primary]
background = "#1e2127"
foreground = "#abb2bf"

[colors.normal]
black = "#5c6370"
red = "#e06c75"
green = "#98c379"
yellow = "#e5c07b"
blue = "#61afef"
magenta = "#c678dd"
cyan = "#56b6c2"
white = "#abb2bf"

[colors.bright]
black = "#5c6370"
red = "#e06c75"
green = "#98c379"
yellow = "#e5c07b"
blue = "#61afef"
magenta = "#c678dd"
cyan = "#56b6c2"
white = "#ffffff"

